on:
  schedule:
   - cron: "*/30 * * * *"
  workflow_dispatch:
    

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: cobraz
          export_default_credentials: true

      - name: Sync issues / Generic
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
          query: archived:false sort:updated-desc assignee:cobraz updated:>2021-01-01 -label:backlog
          storage-bucket: gh-todoist
          sync-file-name: generic.json

      - name: Sync issues / Pull Request
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
          query: is:pr archived:false sort:updated-desc review-requested:cobraz 
          storage-bucket: gh-todoist
          sync-file-name: prs.json
