name: Synchronize Todoist
on:
  schedule:
   - cron: "*/30 * * * *"
  workflow_dispatch:
    

jobs:
  sync_issues:
    name: Synchronize // ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Issues
            query: updated:>2020-06-01 archived:false sort:updated-desc assignee:cobraz -label:backlog
            artifact-name: generic
          - name: Pull Requests
            query: is:pr updated:>2020-06-01 archived:false sort:updated-desc review-requested:cobraz -label:backlog
            artifact-name: pr
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
      
      - name: Decrypt sync
        run: openssl enc -in ./sync.json.enc -d -aes-256-cbc -pass pass:${{ secret.TODOIST_TOKEN }} -out sync.json

      - name: Sync issues
        if: always()
        id: sync
        uses: ./
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
          query: ${{ matrix.query }}
          sync-file-name: ./sync.json
      
      - name: Encrypt sync
        if: always() && steps.sync.outputs.has-changed == 'true'
        run: openssl enc -in sync.json -aes-256-cbc -pass pass:${{ secret.TODOIST_TOKEN }} -out sync.json.enc

      - name: Save artifact
        if: always() && steps.sync.outputs.has-changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: sync.json.enc
